2025-01-19 18:10:29,775 An error occurred
Traceback (most recent call last):
  File "C:\Users\simon\Documents\dark-and-darker-price-searcher\main.py", line 13, in process_image_and_search_price
    imageProcessor = ImageProcessor()
TypeError: ImageProcessor.__init__() missing 2 required positional arguments: 'resolution_height' and 'resolution_width'
2025-01-19 18:10:34,825 An error occurred
Traceback (most recent call last):
  File "C:\Users\simon\Documents\dark-and-darker-price-searcher\main.py", line 13, in process_image_and_search_price
    imageProcessor = ImageProcessor()
TypeError: ImageProcessor.__init__() missing 2 required positional arguments: 'resolution_height' and 'resolution_width'
2025-01-19 18:10:35,789 An error occurred
Traceback (most recent call last):
  File "C:\Users\simon\Documents\dark-and-darker-price-searcher\main.py", line 13, in process_image_and_search_price
    imageProcessor = ImageProcessor()
TypeError: ImageProcessor.__init__() missing 2 required positional arguments: 'resolution_height' and 'resolution_width'
